### ISSUE TITLE
Courses pages

### ISSUE THREAD

**Issue by brandonp1551** [fu-dream-team/frontend#14]
What did we decide about how to handle the multiple courses pages? I.e. are we going to have unique /faculty/courses/ /students/courses and just a general /courses/ pages or should we have them all link to the same /courses/ page?

**Comment by yaja95** [comment]
From what Tartaro said today, it would seem that we could have various pages as long as they contain all the information.

**Comment by brandonp1551** [comment]
I was thinking, based on what she said, that we'll need at least two different pages, one as a list of courses already available and another to suggest/vote on courses.

**Comment by CAD97** [comment]
I think we'll want `/courses` which displays implemented courses, and `/courses/proposed` for the proposed ones. I'll talk a bit with @teslasagna about how we want to model the courses by the end of Friday.

**Comment by CAD97** [comment]
I'll leave it to the frontend team to decide specifics, but I'm currently seeing something like the following: (located at `/courses`)

Display a list of courses, with sections/selections/tabs for past, future approved, and proposed CinC courses

All logged in users have the ability to like courses

Faculty have some way to suggest a course

Though I feel like I'm forgetting required functionality...
